### ISSUE TITLE
Is there any way to change the colour of the graph

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#1]
I am trying to change the colour of the graph that are being drawn, but unsuccessful, so I write to you, please let me know how to change the colour of the graph.

**Comment by taoteh1221** [comment]
Currently there is now way to change the color of the graph, but I will add that as a feature in the next release for you (within about 7 days or less). Thanks very much for the feedback.

**Comment by taoteh1221** [comment]
Chart color changing configurations have been added for inclusion the next release. https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/e602d31baaa573901f5595ffcb0799d1a6870566

**Comment by taoteh1221** [comment]
New release is available for download, that includes changing the chart colors in config.php (just follow the directions in that file to update the color codes in that section): https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases

**Comment by s1-ranjan** [comment]
It would be nice to control the chats background colour  from the default light or dark css file, I fell the default value "#515050" is good for the dark theme whereas the value "#ffffff" would be a good choice for lite theme.
The main issue I faced with the current chats background is that it fits well in only one mode perfectly, by adopting two different chart background will have a much better integration on both the interfaces i.e., dark and light.

**Comment by taoteh1221** [comment]
It would over-complicate the configuration settings so they are more confusing for the non-technically-inclined. We need something that's READIBLE in both themes to keep it simple.
