### ISSUE TITLE
Please update the Zebpay api

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#11]
As of now DFD Cryptocoin is using https://www.zebapi.com/api/v1/market for the Zebpay, and today I discover a new api https://www.zebapi.com/pro/v1/market/ and it provide a much detailed information from Zebpay, so please update it for zebpay.

**Comment by s1-ranjan** [comment]
Can you please add this tickers api for WazirX exchange :  https://api.wazirx.com/api/v2/tickers for crypto-inr pair.

**Comment by taoteh1221** [comment]
Ok, updated the zebpay API and added wazirx. This will be included in the next release v4.16.0 (later today): https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/3c0c55370f5eb092910e647bf87c1d4161f92147

**Comment by s1-ranjan** [comment]
Please add this tickers API for CoinDCX  exchange :  https://public.coindcx.com/exchange/ticker from India.
