### ISSUE TITLE
Allow cronjobs to be executed using external servers

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#13]
I hove noticed my host is causing trouble with the cronjobs setting, they always reset the values to null, so I was thinking if this application have the capability to run the cronjob from external server.

**Comment by taoteh1221** [comment]
See the README.txt file in the main app directory on setting up a cron job properly. If that doesn't help, you should contact your website host's support desk. They should be able to help you get it running properly. Also check your error logs in the app, which may help to see what's going on. Cron jobs are not designed to run from an external server.
