### ISSUE TITLE
Bug in leatest bilt v4.19.0 & v4.19.1

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#16]
There is no proper behavior with Price Change Visual / Audio Alerts: setting from the UI

**Comment by taoteh1221** [comment]
Thanks for the report. I'm not able to replicate this issue. Could you clear your browser cache, and refresh the web page to see if that fixes it? I refactored the functions.js file a week or two ago. If the problem persists after clearing the browser cache, let me know the steps to reproduce the issue on my end, including browser / operating system versions?

**Comment by taoteh1221** [comment]
Also, restart your browser, AFTER clearing the cache.

**Comment by taoteh1221** [comment]
I'm going to presume this was fixed by reloading / refreshing the refactored JavaScript, because of no response for 2 weeks? Closing for now. Let me know if it's still an issue, and I'll reopen this. Thanks for the feedback.

**Comment by s1-ranjan** [comment]
Sorry for delay in my reply to this thread, I found this issue was associated with the folder permissions in my server for the templates and app-lib folder by changing the folder permission to 755 my problem got fixed, but I am observering a new issue related to the graph, the data are not been saved in the server.

**Comment by taoteh1221** [comment]
Any messages in /cache/logs/errors.log log file? Are you sure you're cron job is running ok?

**Comment by taoteh1221** [comment]
/cache/ permission may need to be 777 if your server is a strict setup (which it sounds like it is).

**Comment by s1-ranjan** [comment]
I have seen this error messages:
[2020-10-18 03:07:32] ui => system: HTTP server 'htaccess' support has NOT been enabled on this web server for the 'cache' and 'cron-plugins' sub-directories. 'htaccess' support is required to SAFELY run this application (htaccess security checks are throttled to a maximum of once every hour). ;  
[2020-10-18 03:07:32] ui => system: Server / app setup requirements not met (SEE LOGGED SETUP DEFICIENCIES), exiting application...;  
and moreover I suspect my cron jobs are not working normally, today I have modified my crone job commands in my server and I'll update you after and 24hrs of my observation.

**Comment by s1-ranjan** [comment]
I don't see any new data has been added, so I decided to execute the cron job via the terminal to get an idea of what is going on and I got 
`php /home/ranjan/web/crypto.0or1.ml/public_html/cron.php > /dev/null 2>&1`
`Segmentation fault (core dumped)`
`(core dumped)` error, I am not sure what is wrong, Well I am enclosing the error log from the application [error.log](https://github.com/taoteh1221/DFD_Cryptocoin_Values/files/5397294/error.txt).

**Comment by taoteh1221** [comment]
By looking at the error logs, I presume you successfully enabled htaccess on the server AFTER you saw those warnings? 

Looks like your cron job is running according to log entries, BUT you seem to have issues with either folder permissions, or your disk space is full. Data is not being written to disk in the external API cache. Make sure your 'cache' folder AND ALL FOLDERS / FILES INSIDE IT are set to permission 777, see if that helps.

![Screenshot from 2020-10-19 16-11-45](https://user-images.githubusercontent.com/1760489/96506731-22647c00-1226-11eb-89bf-cf96d83c7f9f.png)

**Comment by taoteh1221** [comment]
A Segmentation fault when you run cron via command line may be you are too low on disk space to run any app that requires cache access (PHP's session cache in this case). It also would explain the failed disk write errors in the log file. Make sure your hosting account has enough reserve storage space before trying anything else.

**Comment by s1-ranjan** [comment]
Finally, I am able to run the latest version on my server but it has flushed all my chart data from the server, so I was thinking it would be nice if this application has an inbuilt function for the import-export of those data so that it can be prevented from any future data loss during the processes of the upgrade.

**Comment by taoteh1221** [comment]
Great news! :smile: 

Chart backup is already built-in. Just make sure you setup your to / from email in config.php, and also set how often to backup charts here (default is once every day): https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/main/config.php#L524

You will then receive an email every X days with a secure download link to backup chart data to your PC. Copies are also saved for X days in /cache/secured/backups/, you can change how long they are saved here (default is delete backups older than 7 days): https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/main/config.php#L528

I have no auto-import built-in yet to restore chart data from these backup files (it's on my TO-DO list), BUT it's pretty easy to import the backups manually. Replace the sub-directories in your /cache/charts/ directory with the same-named directories in the chart backups zip file:

![Screenshot from 2020-10-20 15-36-53](https://user-images.githubusercontent.com/1760489/96635788-55704380-12ea-11eb-80e5-67304f3c1657.png)

**Comment by s1-ranjan** [comment]
Thanks for providing this information I tried to import those data by replacing the subfolder in the chart directory, but the final result took some time to rendered on the screen... so I was expecting if there has been any import feature in the application this would render the result at a much faster rate.. and can prevent a false impression of result not render.

**Comment by taoteh1221** [comment]
It's in my TO-DO list, but I'm taking a break for a few months right now...it won't be added anytime soon, so this is the only method available right now.

**Comment by taoteh1221** [comment]
Your welcome. It took time probably because it was re-building the "lite charts" from the archival charts...having an import feature it would still take just as long.

**Comment by taoteh1221** [comment]
I finally ran into the visual price alerts bug, it will be fixed in the v4.22.2 release coming out later this week. Sorry I wasn't able to replicate the issue until now.
