### ISSUE TITLE
Email push feature for updates.

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#3]
As of now we receive emails alerts for price change in the different exchanges, but we don't receives any mails for the the new version of DFD application, it would be great if the get a email notifications push by DFD directly in our inbox and this can help us to know when a new package is available for upgrade.

**Comment by taoteh1221** [comment]
Thanks again for the feedback. That would require the application to make regular calls to the github API. In the spirit of maximum privacy for end users of this application, all API calls are currently limited to coin network / exchange stats, and price alert push notifications (alexa / text services). That said, I will look into a minimally intrusive implementation of upgrade alerts (will see about emailing, but at least a notification in the web interface seems non-intrusive).

**Comment by taoteh1221** [comment]
@s1-ranjan I will be adding email / alexa / mobile / text upgrade alerts for the app in the upcoming v4.08.0 release (choose one, or all forms of communication in the configuration). Didn't have time to squeeze it in with the v4.07.3 bug fix released today (but I did add basic ING support). The upgrade alert will be optin within the configuration file, so you'll need to enable it (it will be off by default, for user privacy). I'll let you know when v4.08.0 is out with this feature. Thanks for the feedback.

**Comment by s1-ranjan** [comment]
Please add optin option for Theme in the configuration file, by default the application uses dark theme whereas I prefer to use light so it would be nice if it can be controlled from the setting

**Comment by taoteh1221** [comment]
@s1-ranjan Good idea, I'll add setting the default theme in the configuration file next release, thanks for your feedback. I have released v4.07.4 a few minutes ago, which has your requested upgrade alert feature included in it (in config.php). Please let me know if it gives you any issues. https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases

**Comment by taoteh1221** [comment]
@s1-ranjan I've added the default theme feature you wanted into the upcoming v4.08.0 release. I'll let you know when it's out. https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/7efd95c82d9a5c1ff789be2ae721b031f96ee19c

**Comment by taoteh1221** [comment]
@s1-ranjan Closing the upgrade notice feature request, as it's now in the latest release (as well as the default theme setting): https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/master/config.php#L122

Thanks for your feedback, it much appreciated! :smile:
