### ISSUE TITLE
Visual or Audio Alerts setting tweak

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#4]
As of now we have following setting in this section:
Visual or Audio Alerts For Price Changes: Yes/No coingecko.com +5% 1hr/24hrs/7days visual/audio-visual
So, can this +5% can be splited in some thing like this
+/-/±  5%
I mean to say if this value is seplit in two different drop down menu with one menu containing + - and ± as the sign and other menu with the value then we can have a more precise data observation and with the ± option we can have both +ve and -ve values in the Portfolio with their respective colour code.

**Comment by taoteh1221** [comment]
@s1-ranjan Good idea, I see what you mean...have both negative and positive changes show at the same time. I will look into implementing this, thanks for the feedback.

**Comment by taoteh1221** [comment]
@s1-ranjan I'll be adding the visual alerts upgrade sometime within the next couple of releases, I have written a few thousand lines of new code over the past couple months, and am still completing a review of it all (to find any bugs I missed). I'll let you know when it's added to the app, thanks again for you great user feedback. :+1:

**Comment by taoteh1221** [comment]
@s1-ranjan I finally finished the code review on the heavy work done since last december, and have finally had time to add the feature request you wanted for showing gain / loss visual alerts simultaneously. This will be included in the next release within a few days: https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/1c3c238df3bc00c9bbe434e47dfdcfbb2d26423e

Thanks for your feedback, this was a great idea for a feature! :+1:

**Comment by taoteh1221** [comment]
@s1-ranjan v4.09.2 is now available for download, which includes the visual / audio alerts showing gain and loss simultaneously: https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases

**Comment by s1-ranjan** [comment]
Inset of using `<span style="color: #6ead6e;">+</span><span style="color: #dd7c0d;">-</span>` following code can have a better output `<span style="color: #6ead6e;"><sup>+</sup></span>&frasl;<span style="color: #dd7c0d;"><sub>-</sub></span>` 
for the both type of result under portfolio tab.
Above code can be a much closer representation of the fractional representation of the both the value.

**Comment by taoteh1221** [comment]
Sorry for the wait. Great idea, thanks! :) I just added this too, and released v4.14.7 with it included: https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases

**Comment by s1-ranjan** [comment]
I don't find it to be 100% accurate  with ![pm](https://user-images.githubusercontent.com/20767253/86531397-608b9900-bede-11ea-8220-8db8094df51e.png), so I tried to create a .svg file that can solve this issue, because I thought this svg files can be easily manipulated with css to add different colours in the future versions...
[pm.tar.gz](https://github.com/taoteh1221/DFD_Cryptocoin_Values/files/4874807/pm.tar.gz)

**Comment by taoteh1221** [comment]
Good idea, thanks! :) I just added that into the upcoming release: https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/7fe604478c151f2569221e40f3cdc49d2685e1cb
