### ISSUE TITLE
Request for telegram support

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#5]
I wish to get the update on my mobile and I was thinking if these updates can be pushed to mobile via telegram then it can be great.

**Comment by taoteh1221** [comment]
Have you tried setting your mobile carrier in the configuration? I already have upport for text gateways in India. See the below-linked sections of the config file:

Setting your mobile number carrier: https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/master/config.php#L58

Finding your mobile carrier on the list: https://github.com/taoteh1221/DFD_Cryptocoin_Values/blob/master/config.php#L708

Let me know if your carrier is not listed, and I will add them.

**Comment by s1-ranjan** [comment]
It did not work for me, so I thought to go with telegram.

**Comment by s1-ranjan** [comment]
I think this feature is a old method which was there in the past but in present time this feature is no longer available from my carrier in India.
I found this link https://www.bsnl.co.in/opencms/bsnl/BSNL/services/broadband/sms.html 
but the site : www.sancharnet.in is not opening, So I fell they may have rolled out this service.

**Comment by taoteh1221** [comment]
sms.sancharnet.in does not have an email server setup in it's mail server records, so it is not running anymore. You could try textbelt or textlocal, I currently support both (see the top of config.php in the latest v4.07.7 release). I will be adding twilio and clicksend support sometime this year too.

Good news on telegram though, I was able to easily integrate it into the app today...it will be included in v4.07.8 sometime within the next few days (I'll let you know when it's released). Thanks again for the great ideas Rai! :smile:  https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/c7af5dd4e0bc8a6c97e0f80587fbc3b143316049

**Comment by s1-ranjan** [comment]
Basically there are two main reasons for asking support for telegram:
1. Indian government is not supporting the crypto currency, as of now.
2. Encryption technology makes the messages more secure.

**Comment by taoteh1221** [comment]
Yes, I have heard the news they may ban crypto in India. I hope Charlie Shrem talked some sense into the Indian official he met with last year. Fingers crossed. The telegram feature works great, just have to tighten the security on it a little bit, then I will release the upgrade.

**Comment by taoteh1221** [comment]
Rai, the release with telegram support is available for download now. Please let me know if you have any issues with telegram alerts in this release? Closing this issue for now, will reopen if any telegram problems occur for you. Thanks for your feedback, this feature was a very good idea. :+1:

**Comment by taoteh1221** [comment]
@s1-ranjan There will b a bug fix release v4.07.9 within a few days, to fix a few bugs in the telegram messaging feature. I'll let you know when it's released. There was an issue where I was persistantly storing the telegram user id, so a day or two after activating your messaging it may stop working. This has been fixed in v4.07.9. https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/f0d71e5a4bd55daf04753d917041652b962b4750

**Comment by taoteh1221** [comment]
@s1-ranjan Telegram messaging support bug fix release is out: https://github.com/taoteh1221/DFD_Cryptocoin_Values/releases
