### ISSUE TITLE
Please add following coins in portfolio assets

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#6]
Please add few more coins in the portfolio assets and in chart section
1. DASH
2. ZEC
3. BAT

**Comment by taoteh1221** [comment]
Hello @s1-ranjan I don't add particular coin requests to the example assets list, as those are only demos to test drive the app, before adding your own coins. See the bottom of the README file on how to add any coins you want, that are available on the supported exchanges: https://raw.githubusercontent.com/taoteh1221/DFD_Cryptocoin_Values/master/README.txt

That said, later this year I will have an admin config login webpage interface integrated, to make adjusting settings much easier than editing config.php by hand...including updating the coins list.
