### ISSUE TITLE
It would be nice if we have a page for market

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#8]
It would be great if we have a separate page for market that would list top 100 or 200 coins in one page with following type of details

  | Chose your market source | Coingecko.com / Coinmarketcap.com |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   | Changes in the market |   |   |   |   |   |  
Ranking | Coin / Token | Global Average value | 1 hrs | 24 hrs | 7 days | 14 days | 30 days | 200 days | 1 year
1 | Bitcoin |   |   |   |   |   |   |   |  
2 | Ethereum |   |   |   |   |   |   |   |  

We already have the API calls to the both the market and we just required to accommodate those value in a separate page, this will give a good overview of the crypto market at one place.

**Comment by taoteh1221** [comment]
My primary goal with this app is to keep it as minimal / simple as possible, to avoid confusion and be very easy to use. A user can already click on each asset name to visit it's coingecko / coinmarketcap page, and then they can click the main page once on those sites to see a MUCH BETTER MARKETCAP LIST than they could get anywhere else in the world. 

That said, thanks very much for taking the time to submit the idea. It's just not feasible with coingecko / coinmarketcap already offering that.

**Comment by s1-ranjan** [comment]
I partially agree with you, but DFD_Cryptocoin_Values relies on those two websites for the data and having a market page in this application will just provide a overview of two different market places without leaving this app and more over this application will provide a simpler view of two different markets. Whereas the parents site will provide a much detailed market details.

**Comment by taoteh1221** [comment]
We need to save space for more feasible / relevant features in the interface, other than features that are currently much better on offsite apps. You have to keep an interface simple and minimal so people using an app find it easy and not confusing with TOO MANY FEATURES. This is a real problem many developers fail to see. Simpler is ALWAYS better, if you want people to really use the app alot. 

I don't mean to come across rude, I really do appreciate user feedback VERY MUCH. Thank you @s1-ranjan for your input, I'm glad you enjoy the app enough to comment on it's development. :smiley:
