### ISSUE TITLE
Buyucoin is using new API

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/DFD_Cryptocoin_Values#9]
I have seen today that Buyucoin is using new API and they have dropped the old API so please fix those and documentation is available at:
https://documenter.getpostman.com/view/2739249/Szme5eNF?version=latest

**Comment by taoteh1221** [comment]
Thanks for reporting this. Sorry it took so long to get to it, I have MANY bug fixes coming up in the next release I was very busy doing. I have updated the buyucoin API logic, it will be included in the next release (will be released tomorrow): https://github.com/taoteh1221/DFD_Cryptocoin_Values/commit/e8c21163844d3117670303a5df5730bd7a91d748
